name: tour_with_tourapi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.2

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  flutter_localizations:
    sdk: flutter
  geolocator: ^10.0.0
  http:
  flutter_naver_map: ^1.0.0
  provider: ^6.0.5
  loading_animation_widget:
  flutter_widget_from_html: ^0.10.5+3
  kakao_map_plugin: ^0.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/appicon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/appicon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "lib/assets/appicon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/appicon.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

