name: tour_with_tourapi
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0-163.1.beta <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  fluttertoast: ^8.2.2
  scroll_date_picker: ^3.7.3
  intl: ^0.18.1

flutter:
  uses-material-design: true
  assets:
    - lib/assets/

